address: "localhost"
port: 8080
viewsDir: "/views"
routes: "./routes/routes"
langDir: "/locales"
langSet: ["es","en"]
dbAddress: "localhost"
dbName: "sportmanager"
dbNameJobs: "sportmanager-jobs"
timeRss: "10 minutes"
timeStatePlayers: "6 hours"
mockMode: 1